### PR TITLE
Update default_spec.rb | Signed-off-by:aria1991

### PR DESCRIPTION
**Pull request by aria1991**
# Description

I refactored the code and made some changes:

This has more descriptive test cases, and uses subject to make the code more concise. It also groups related tests together using `describe.one`.

### CODE REVIEW

**Review by xorima — APPROVED** [review]

**Comment by xorima** [comment]
Hey,

Can you update the change log file as well so we can get this merged? 

Thanks

**Comment by aria1991** [comment]
> Hey,
> 
> Can you update the change log file as well so we can get this merged?
> 
> Thanks

Hey. Done!

**Comment by damacus** [comment]
@aria1991 I thnk you updated the changelog in the wrong repo :)

**Comment by aria1991** [comment]
> @aria1991 I thnk you updated the changelog in the wrong repo :) oh really? My bad :D

**Comment by aria1991** [comment]
> @aria1991 I thnk you updated the changelog in the wrong repo :)

 oh really? My bad :D

**Comment by damacus** [comment]
Please rebase :)

**Comment by damacus** [comment]
Merging into #473

**Pull request closed without merging**
